name: CI/CD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create directories
        run: mkdir -p src/main/resources/

      - name: Set up application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build

#      - name: List build directory recursively
#        run: ls -alR build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: build/libs/*.jar

#      - name: List build/libs directory
#        run: ls -al build/libs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: build

      - name: Create remote temporary directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.REMOTE_DIR }}

#      - name: List build/libs directory
#        run: ls -alR build
#
#      - name: Find diva-0.0.1-SNAPSHOT.jar
#        run: find . -type f -name "diva-0.0.1-SNAPSHOT.jar"
#
#      - name: Find diva-0.0.1-SNAPSHOT.jar in entire system
#        run: sudo find / -type f -name "diva-0.0.1-SNAPSHOT.jar" 2>/dev/null


      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/diva-0.0.1-SNAPSHOT.jar"
          target: ${{ secrets.REMOTE_DIR }}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        env:
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Stopping any running Java application..."
            pkill -f "java -jar ${REMOTE_DIR}/" || echo "No running Java process found."
            sleep 5

            echo "Searching for the latest JAR file in ${REMOTE_DIR}..."
            JAR_FILE=$(ls -t ${REMOTE_DIR}/build/diva-0.0.1-SNAPSHOT.jar | head -n 1)
            echo "Deploying JAR file: $JAR_FILE"

            echo "Starting the application..."
            nohup java -jar $JAR_FILE > ${REMOTE_DIR}/build/app.log 2>&1 &
            echo "Deployment complete."
