name: CI/CD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create directories
        run: mkdir -p src/main/resources/

      - name: Set up application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: build

      - name: Create remote temporary directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.REMOTE_DIR }}

      - name: List build/libs directory
        run: ls -al build/libs/

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: ${{ secrets.REMOTE_DIR }}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            
            echo "Stopping any running Java application..."
            # 실행 중인 애플리케이션 종료; 실행 중이 없으면 오류를 무시합니다.
            pkill -f "java -jar ${secrets.REMOTE_DIR}/" || echo "No running Java process found."
            sleep 5
            
            echo "Searching for the latest JAR file in ${secrets.REMOTE_DIR}..."
            JAR_FILE=$(ls -t ${secrets.REMOTE_DIR}/*.jar | head -n 1)
            echo "Deploying JAR file: $JAR_FILE"
            
            echo "Starting the application..."
            nohup java -jar $JAR_FILE > ${secrets.REMOTE_DIR}/app.log 2>&1 &
            echo "Deployment complete."
